//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoList.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYNCQUEUE
    {
        public int id { get; set; }
        public int evenid { get; set; }
        public bool status { get; set; }
        public int type { get; set; }
    }
}
